### PR TITLE
352 - Practice App - API - Frontend - Product Page

### LINKED ISSUE #123: Complete productpage.html
Complete the html document for the product page and merge the branch to the master branch.

### PR DESCRIPTION
**Pull request by yagizcolak**
The product page 'product_page.html' is ready to be merged to the master branch.

### CODE REVIEW

**Comment by utulb** [comment]
The HTML page is sufficient for the practice API.

**Comment by memetc** [comment]
Keep up the good work.

**Review by memetc — APPROVED** [review]
The page is able to display products and a link is provided to add a comment to a specific product.

**Review by AsenaKarolin — APPROVED** [review]
The product page is sufficient and this branch does not conflict with the master branch. This branch seems to be ready to be merged to the master branch.

**Review by utulb — APPROVED** [review]
The comments of product HTML page seems sufficient and it is ready to merge with the master branch.

**Pull request merged**
