### PR TITLE
Practice App: Search endpoint

### LINKED ISSUE #99: Implement the backend code for search endpoint for the practice-app
Implement the Flask blueprint for the search endpoint in the practice-app.

### PR DESCRIPTION
**Pull request by onurkilic2301**
Implemented the Flask blueprint for the search endpoint in the practice-app.

### CODE REVIEW

**Comment by muratekici** [comment]
I looked over the code and it is good to go, also there are no conflicts.

**Review by lighterm — APPROVED** [review]
I looked over the code and it is good to go, also there are no conflicts. We just might change the 8th line a bit(name of the blueprint) for convention and readability.

**Review by barissmutluuu — APPROVED** [review]
it looks okay

**Review by barisalhan — APPROVED** [review]
Thanks for the great work! In general, writing comments above the line could be more readable instead of writing in the same line. Because many developers use half of the monitor for coding while using another half for other things. Therefore, it is important to not exceed 100 characters in each line. Also, spacing could be adjusted to increase readability. All in all, thanks for the work.

**Pull request merged**
