### PR TITLE
HTML page for creating new products

### LINKED ISSUE #131: Complete createP.html
HYML page for creating a new product

### PR DESCRIPTION
**Pull request by memetc**
Location field is added and ready to be reviewed.

### CODE REVIEW

**Review by yagizcolak — APPROVED** [review]
Creating new products page look neat and sufficient to me. It is compatible with the other html codes. Keep up the good work.

**Review by AsenaKarolin — APPROVED** [review]
The html page for creating new products is adequate and compatible with the rest of the project and the branch does not have any conflicts with the master branch. I think that it is ready to be merged.

**Review by utulb — COMMENTED** [review]
The create new product HTML page seems sufficient and it is ready to merge with the master branch.

**Review by utulb — APPROVED** [review]
The create new product HTML page seems sufficient and it is ready to merge with the master branch.

**Review by utulb — APPROVED** [review]
The create new product HTML page seems sufficient and it is ready to merge with the master branch.

**Pull request merged**
