### PR TITLE
352 - Practice App - API - Frontend - Home Page

### LINKED ISSUE #119: Complete home.html
Complete the html document for the homepage and merge the branch to the master branch.

### PR DESCRIPTION
**Pull request by AsenaKarolin**
The home page 'home.html' is ready to be merged to the master branch.

### CODE REVIEW

**Review by memetc — APPROVED** [review]
Front-end of the home page of the practice api seems sufficient. Products are displayed here and the page fits the overall layout.

**Comment by Tulkas14** [comment]
Home page for our practice api seems adequate to me. It is compatible with other html pages. It looks simple and neat.

**Review by yagizcolak — COMMENTED** [review]
Home page for our practice api seems adequate to me. It is compatible with other html pages. It looks simple and neat.

**Review by yagizcolak — APPROVED** [review]
Home page for our practice api seems adequate to me. It is compatible with other html pages. It looks simple and neat.

**Comment by utulb** [comment]
Home page HTML doesn't have any problem for the practice API. It is suitable for its purpose.

**Pull request merged**
